Em
ECellNitrr/EcellWeb2k22 pull request #32
Opened 2022-10-16 06:34 UTC by Shubhambawner

Team page updated 
now its more dynamic, componentised, and error tollerent.
EM added.

2022-10-16 06:40 UTC, Shubhambawner commented
resolves #28 
partially resolves #27

2022-10-16 06:41 UTC, Shubhambawner commented
@AyushAgrawal25 @rajesh6161

2022-10-16 08:15 UTC, sahil9001 commented
> resolves #28 
> 
> partially resolves #27 

One PR should resolve one issue because when we have to revert we can't revert separately.

2022-10-16 09:44 UTC, sahil9001 requested changes

2022-10-16 09:44 UTC, sahil9001 commented on src/Components/Team/descriptions.js
> +    em: 'Event Management',
Add Video editing domain as 've'

2022-10-16 13:50 UTC, Shubhambawner commented
> > resolves #28
> > partially resolves #27
> 
> One PR should resolve one issue because when we have to revert we can't revert separately. @Shubhambawner revert #27 changes and keep this PR as #28 only.

Oh yes, after some examination I found that issue 27 is independent. initially it was incorrectly linked.

2022-10-16 13:55 UTC, Shubhambawner commented on src/Components/Team/descriptions.js
> +    em: 'Event Management',
done

2022-10-22 08:07 UTC, sahil9001 commented
@AyushAgrawal25 I haven't tested these files but looks good to me, can you check it?

2022-10-25 12:54 UTC, AyushAgrawal25 approved these changes
LGTM 
I am merging the changes.

2022-10-25 12:56 UTC, AyushAgrawal25 requested changes
Change the base_url at axios.js to https://ecellbackend.tech/, currently it's causing merge issue.

2022-10-25 13:33 UTC, merged